import type { Effect } from "effect";
import { Context } from "effect";
import type { InfrastructureFailure } from "./cms-error.ts";

/** The closed vocabulary of identifiers generated by the CMS. */
export type Kind =
  | "entry"
  | "asset"
  | "write-token"
  | "snapshot"
  | "migration"
  | "request"
  | "idempotency";

/** Builder-supplied opaque identifier generation capability. */
export class Generator extends Context.Service<
  Generator,
  {
    readonly generate: (kind: Kind) => Effect.Effect<string, InfrastructureFailure>;
  }
>()("nearly-headless-cms/Identifier/Generator") {}
