import type {
  GeneratedOperation,
  GeneratedSuccessResponse,
  Parameter,
  ParsedOpenApiDocument,
} from "./operations.ts";
import { renderComponentTypes, renderSchemaType, renderTypeProperty } from "./schema-types.ts";
import {
  runtimeAfterMakeGeneratedClient,
  runtimeBeforeSpecifications,
  runtimeConstChainMiddle,
  runtimeRequestOperation,
} from "./runtime-template.ts";

interface GenerateClientSourceInput extends ParsedOpenApiDocument {
  readonly formatVersion: number;
}

interface ParameterGroup {
  readonly required: boolean;
  readonly type: string;
}

interface SourceRenderer {
  readonly appendParameterGroup: (
    fields: string[],
    name: "headers" | "path" | "query",
    group: ParameterGroup | null,
  ) => void;
  readonly appendRequestBody: (fields: string[], operation: GeneratedOperation) => void;
  readonly generate: (input: GenerateClientSourceInput) => string;
  readonly operationInputType: (operation: GeneratedOperation) => string;
  readonly operationResponseType: (operation: GeneratedOperation) => string;
  readonly operationSpecifications: (
    operations: readonly GeneratedOperation[],
  ) => Readonly<Record<string, unknown>>;
  readonly parameterGroupType: (
    parameters: readonly Parameter[],
    location: Parameter["location"],
  ) => ParameterGroup | null;
  readonly propertyField: (name: string, type: string, required: boolean) => string;
  readonly successResponseType: (response: GeneratedSuccessResponse) => string;
}

const emptyItemCount = 0,
  jsonIndentation = 2,
  sourceRenderer: SourceRenderer = {
    appendParameterGroup(fields, name, group) {
      if (group === null) {
        return;
      }
      fields.push(`readonly ${this.propertyField(name, group.type, group.required)}`);
    },
    appendRequestBody(fields, operation) {
      if (operation.requestBodySchema === undefined) {
        return;
      }
      let bodyType = renderSchemaType(operation.requestBodySchema);
      if (operation.requestMediaType === "multipart/form-data") {
        bodyType = "FormData";
      }
      fields.push(
        `readonly ${this.propertyField("body", bodyType, operation.requestBodyRequired)}`,
      );
    },
    generate({ document, formatVersion, operations }) {
      const componentTypes = renderComponentTypes(document),
        inputTypes = operations
          .map(
            (operation) =>
              `  readonly ${operation.identifier}: ${this.operationInputType(operation)};`,
          )
          .join("\n"),
        operationMethods = operations
          .map(
            (operation) =>
              `  ${operation.identifier}: createOperationMethod(baseAddress, "${operation.identifier}"),`,
          )
          .join("\n"),
        responseTypes = operations
          .map(
            (operation) =>
              `  readonly ${operation.identifier}: ${this.operationResponseType(operation)};`,
          )
          .join("\n"),
        specifications = JSON.stringify(
          this.operationSpecifications(operations),
          null,
          jsonIndentation,
        );
      return `// Generated by scripts/openapi-client-generator.ts. Do not edit.\nimport { Effect, Schema } from "effect";\nimport { DeclaredFailure } from "./declared-failure.ts";\nimport { ProtocolFailure } from "./protocol-failure.ts";\nimport { TransportFailure } from "./transport-failure.ts";\n\nexport { DeclaredFailure } from "./declared-failure.ts";\nexport { ProtocolFailure } from "./protocol-failure.ts";\nexport { TransportFailure } from "./transport-failure.ts";\n\n${componentTypes}\n\nexport interface OperationInputs {\n${inputTypes}\n}\n\nexport interface OperationResponses {\n${responseTypes}\n}\n\ninterface OperationSpecification {\n  readonly method: string;\n  readonly path: string;\n  readonly requestMediaType?: string;\n  readonly successResponses: readonly {\n    readonly responseMediaType?: string;\n    readonly status: number;\n  }[];\n}\n\n${runtimeBeforeSpecifications}generatorFormatVersion = ${formatVersion},${runtimeConstChainMiddle}makeGeneratedClient = (baseAddress = "") => ({\n${operationMethods}\n  }),\n  operationSpecifications = ${specifications} satisfies Readonly<Record<keyof OperationInputs, OperationSpecification>>${runtimeAfterMakeGeneratedClient};\n\n${runtimeRequestOperation}\nexport { generatorFormatVersion, makeGeneratedClient };\n`;
    },
    operationInputType(operation) {
      const fields: string[] = [],
        headerType = this.parameterGroupType(operation.parameters, "header"),
        pathType = this.parameterGroupType(operation.parameters, "path"),
        queryType = this.parameterGroupType(operation.parameters, "query");
      this.appendParameterGroup(fields, "path", pathType);
      this.appendParameterGroup(fields, "query", queryType);
      this.appendParameterGroup(fields, "headers", headerType);
      this.appendRequestBody(fields, operation);
      if (fields.length === emptyItemCount) {
        return "Readonly<Record<never, never>>";
      }
      return `{ ${fields.join("; ")} }`;
    },
    operationResponseType(operation) {
      return [
        ...new Set(
          operation.successResponses.map((response) => this.successResponseType(response)),
        ),
      ].join(" | ");
    },
    operationSpecifications(operations) {
      return Object.fromEntries(
        operations.map((operation) => [
          operation.identifier,
          {
            method: operation.method,
            path: operation.path,
            requestMediaType: operation.requestMediaType,
            successResponses: operation.successResponses.map(({ mediaType, status }) => ({
              responseMediaType: mediaType,
              status,
            })),
          },
        ]),
      );
    },
    parameterGroupType(parameters, location) {
      const selectedParameters = parameters.filter((parameter) => parameter.location === location);
      if (selectedParameters.length === emptyItemCount) {
        return null;
      }
      return {
        required: selectedParameters.some((parameter) => parameter.required),
        type: `{ readonly ${selectedParameters
          .map((parameter) =>
            this.propertyField(
              renderTypeProperty(parameter.name),
              renderSchemaType(parameter.schema),
              parameter.required,
            ),
          )
          .join("; readonly ")} }`,
      };
    },
    propertyField(name, type, required) {
      let optionalSuffix = "?";
      if (required) {
        optionalSuffix = "";
      }
      return `${name}${optionalSuffix}: ${type}`;
    },
    successResponseType(response) {
      if (response.schema === undefined) {
        return "undefined";
      }
      if (response.mediaType === "application/octet-stream") {
        return "Uint8Array";
      }
      return renderSchemaType(response.schema);
    },
  },
  zGenerateClientSource = (input: GenerateClientSourceInput): string =>
    sourceRenderer.generate(input);

/** Emits the stable TypeScript source for a validated OpenAPI document. */
export { zGenerateClientSource as generateClientSource };
