const chunkOperationCount = 15,
  emptyItemCount = 0,
  generatedFileBanner = "// Generated by scripts/openapi-client-generator.ts. Do not edit.\n",
  jsonIndentation = 2;

export { chunkOperationCount, emptyItemCount, generatedFileBanner, jsonIndentation };
