export type VerificationLevel =
  | "unit"
  | "type"
  | "contract"
  | "integration"
  | "filesystem"
  | "journey"
  | "visual"
  | "manual"
  | "package"
  | "architecture";

export interface AcceptanceCase {
  readonly id: string;
  readonly source: string;
  readonly claim: string;
  readonly level: VerificationLevel;
  readonly owner: "library" | "example-cms" | "public-blog" | "cross-system";
  readonly command: string;
  readonly selector: string;
  readonly runtime: string;
  readonly operatingSystem: string;
  readonly adapter: string;
  readonly externalProcess: string;
  readonly automation: "automated" | "manual";
  readonly evidence: readonly string[];
  readonly limitation?: string;
}

const automated = (
    id: string,
    source: string,
    claim: string,
    level: VerificationLevel,
    owner: AcceptanceCase["owner"],
    command: string,
    selector: string,
    adapter = "memory",
  ): AcceptanceCase => ({
    adapter,
    automation: "automated",
    claim,
    command,
    evidence: ["test result", "command log"],
    externalProcess:
      level === "journey" || level === "visual" ? "Example CMS and Public Blog" : "none",
    id,
    level,
    operatingSystem: "portable unless named",
    owner,
    runtime: "Bun 1.4.0",
    selector,
    source,
  }),
  manual = (id: string, source: string, claim: string, selector: string): AcceptanceCase => ({
    adapter: "filesystem",
    automation: "manual",
    claim,
    command: "docs/manual/v0.1-release-checklist.md",
    evidence: ["signed release-candidate checklist"],
    externalProcess: "Safari, Chrome, Firefox, VoiceOver, Japanese IME",
    id,
    level: "manual",
    limitation:
      "Claim is limited to the recorded versions and macOS desktop keyboard/mouse authoring.",
    operatingSystem: "macOS",
    owner: "cross-system",
    runtime: "Bun 1.4.0",
    selector,
    source,
  });

export const acceptanceCases: readonly AcceptanceCase[] = [
  automated(
    "DEF-001",
    "issue #21",
    "Complete serializable snapshots compile deterministically and invalid graphs leave the active snapshot unchanged.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit",
    "ContentDefinition.compile",
  ),
  automated(
    "DEF-002",
    "issue #21",
    "Definition identifiers, Field Group cycles, collisions, unknown kinds, and fingerprints are validated.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit",
    "ContentDefinition graph validation",
  ),
  automated(
    "FLD-001",
    "issue #15",
    "Built-in Field Kinds validate without coercion and creation-only defaults never appear on update.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test",
    "Cms.Service validation",
  ),
  automated(
    "FLD-002",
    "issue #15",
    "Single scalar uniqueness is enforced atomically among live Entries.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test/integration",
    "unique values",
  ),
  automated(
    "ENT-001",
    "issue #2",
    "Create, get, complete replacement, delete, and query use one Content Type and stable Entry representations.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test/integration",
    "Cms.Service",
  ),
  automated(
    "QRY-001",
    "issue #2",
    "Portable predicates, boolean groups, sorting, projection, limits, and deterministic Cursor pages never approximate.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit/entry-query.test.ts",
    "EntryQuery.evaluate",
  ),
  automated(
    "QRY-002",
    "issue #2",
    "Stale, invalid, or differently bound Cursors return a typed failure.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit/entry-query.test.ts",
    "cursor binding",
  ),
  automated(
    "REL-001",
    "issue #11",
    "Relationship targets validate atomically and inbound live references restrict deletion without referrer disclosure.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test/integration",
    "Relationship integrity",
  ),
  automated(
    "REL-002",
    "issue #11",
    "Relationship Expansion is explicit, bounded, cycle-safe, and separately authorized once.",
    "contract",
    "library",
    "bun test packages/nearly-headless-cms/test/contract",
    "authorization and expansion",
  ),
  automated(
    "HIS-001",
    "issue #16",
    "History-enabled mutations create immutable revisions with opaque Write Tokens and stale writes change nothing.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test/integration",
    "history-aware concurrency",
  ),
  automated(
    "HIS-002",
    "issue #16",
    "Deletion records, restoration, retention, and Permanent Purge preserve the settled state machine.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test/integration",
    "history state transitions",
  ),
  automated(
    "MIG-001",
    "issue #10",
    "One-to-one Migration Handlers prepare fully valid target Entries and preparation becomes stale after a source write.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit/definition-migration.test.ts",
    "DefinitionMigration.prepare",
  ),
  automated(
    "MIG-002",
    "issue #10",
    "Migration graphs admit at most one directed path and rollback is an explicit forward edge.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit/definition-migration.test.ts",
    "DefinitionMigration.validateGraph",
  ),
  automated(
    "RTX-001",
    "issue #17",
    "Core semantic Rich Text validates placement, marks, references, and visibly rejects unsupported extensions.",
    "unit",
    "library",
    "bun test packages/nearly-headless-cms/test/unit/rich-text.test.ts",
    "RichText",
  ),
  automated(
    "RTX-002",
    "issue #6",
    "The app-owned editor normalizes semantic transactions and preserves bounded undo/redo across save.",
    "unit",
    "example-cms",
    "bun test apps/example-cms/test/unit/rich-text-editor.test.ts",
    "RichTextEditor",
  ),
  automated(
    "IDN-001",
    "issue #13",
    "Every request has explicit Anonymous or opaque Actor identity with no library User model.",
    "type",
    "library",
    "bun run test:types",
    "CurrentIdentity",
  ),
  automated(
    "AUT-001",
    "issue #13",
    "Generic operations authorize at the public seam before lookup and expose no trusted bypass.",
    "contract",
    "library",
    "bun test packages/nearly-headless-cms/test/contract",
    "authorization ordering",
  ),
  automated(
    "FSP-001",
    "issue #19",
    "The Bun filesystem Adapter recovers immutable committed generations after restart.",
    "filesystem",
    "library",
    "bun test packages/nearly-headless-cms/test/filesystem",
    "restart recovery",
    "Bun filesystem",
  ),
  automated(
    "FSP-002",
    "issue #19",
    "Asset Blobs are streamed, bounded, digest-addressed, and verified on read.",
    "filesystem",
    "library",
    "bun test packages/nearly-headless-cms/test/filesystem",
    "Asset digest",
    "Bun filesystem",
  ),
  automated(
    "FSP-003",
    "issue #19",
    "One writer, exact staging cleanup, format markers, and atomic/durable acknowledgement failures are structured.",
    "filesystem",
    "library",
    "bun test packages/nearly-headless-cms/test/filesystem",
    "writer and recovery",
    "Bun filesystem",
  ),
  automated(
    "HTTP-001",
    "issue #9",
    "Management and Headless contracts have separate versioned routes, direct bodies, headers, errors, and OpenAPI 3.1 documents.",
    "contract",
    "library",
    "bun test packages/nearly-headless-cms/test/contract/http-contract.test.ts",
    "HTTP contract",
  ),
  automated(
    "HTTP-002",
    "issue #9",
    "Headless routes expose only composed Delivery Operations and never unrestricted CRUD or generic Query.",
    "contract",
    "library",
    "bun test packages/nearly-headless-cms/test/contract/http-contract.test.ts",
    "Headless absence",
  ),
  automated(
    "HTTP-003",
    "issue #9",
    "Asset delivery uses immutable ETags, HEAD, one range, safe filenames, and 200/206/304/416 semantics.",
    "integration",
    "library",
    "bun test packages/nearly-headless-cms/test/integration",
    "Asset HTTP",
  ),
  automated(
    "GEN-001",
    "issue #6",
    "Canonical OpenAPI documents and separate app-local generated clients are deterministic.",
    "architecture",
    "cross-system",
    "bun run check:generated",
    "generated artifacts",
  ),
  automated(
    "CMS-001",
    "issue #5",
    "The Example CMS defines Posts, Authors, Categories, Tags, Assets, and moderated Comments with deterministic seed content.",
    "integration",
    "example-cms",
    "bun test apps/example-cms/test/integration",
    "Example Blog domain",
  ),
  automated(
    "CMS-002",
    "issue #18",
    "The responsive workbench exposes overview, queues, lists, Entry editors, Assets, history, and static-boundary state.",
    "visual",
    "example-cms",
    "bun run test:visual",
    "CMS visual baselines",
  ),
  automated(
    "BLOG-001",
    "issue #5",
    "The static Public Blog exports only published Posts and approved Comments across all route families and RSS.",
    "integration",
    "public-blog",
    "bun run --cwd apps/public-blog build",
    "Astro static routes",
    "Headless HTTP",
  ),
  automated(
    "BLOG-002",
    "issue #18",
    "Static pages work without JavaScript; Comment enhancement is the sole browser-time content mutation.",
    "architecture",
    "public-blog",
    "bun run check:architecture",
    "Public Blog boundary",
  ),
  automated(
    "E2E-001",
    "issue #4",
    "A coherent public export builds the complete site and an unavailable export cannot replace prior output.",
    "journey",
    "cross-system",
    "bun run acceptance",
    "static export journey",
    "filesystem and Headless HTTP",
  ),
  automated(
    "VIS-001",
    "issue #4",
    "CMS and Public Blog critical states match baselines at 390×844, 768×1024, and 1440×1000.",
    "visual",
    "cross-system",
    "bun run test:visual",
    "visual baselines",
  ),
  automated(
    "A11Y-001",
    "issue #4",
    "Critical pages expose semantic landmarks, headings, names, linked validation errors, focus visibility, and live status.",
    "journey",
    "cross-system",
    "bun run test:webview",
    "semantic and keyboard journey",
  ),
  automated(
    "PKG-001",
    "issue #20",
    "The exact 0.1.0 archive contains only allowlisted ESM, declarations, maps, metadata, docs, and identical MIT licensing.",
    "package",
    "library",
    "bun run --cwd packages/nearly-headless-cms package:inspect",
    "archive inspection",
  ),
  automated(
    "PKG-002",
    "issue #20",
    "The same archive installs, typechecks, and runs every import under Bun and portable imports under Node.",
    "package",
    "library",
    "bun run --cwd packages/nearly-headless-cms package:smoke",
    "clean consumer",
  ),
  automated(
    "COMP-001",
    "issue #20",
    "Portable entry points contain no Bun-only import or declaration while the filesystem subpath is explicit.",
    "architecture",
    "library",
    "bun run check:architecture",
    "runtime isolation",
  ),
  automated(
    "ARCH-001",
    "issue #14",
    "Exactly three workspaces preserve the library → CMS → HTTP-only Content Client dependency direction.",
    "architecture",
    "cross-system",
    "bun run check:architecture",
    "workspace topology",
  ),
  manual(
    "A11Y-002",
    "issue #4",
    "VoiceOver completes landmarks, controls, dialogs, validation, editor toolbar, and Comment receipt flows.",
    "VoiceOver protocol",
  ),
  manual(
    "RTX-003",
    "issue #6",
    "Japanese Hiragana IME, native selection, and plain-text clipboard editing survive save and reload.",
    "IME and clipboard protocol",
  ),
  manual(
    "COMP-002",
    "issue #4",
    "Critical flows pass current Safari, Chrome, and Firefox with the Public Blog also checked without JavaScript.",
    "cross-browser protocol",
  ),
];
