import { Schema } from "effect";

export const EmptyRequest = Schema.Struct({}),
  Identifier = Schema.String,
  PageQuery = {
    cursor: Schema.String,
    pageSize: Schema.Int,
  },
  RichTextDocument = Schema.JsonObject,
  PublicPost = Schema.Struct({
    author: Schema.String,
    body: RichTextDocument,
    categories: Schema.Array(Schema.String),
    excerpt: Schema.String,
    featuredAlternativeText: Schema.NullOr(Schema.String),
    featuredAsset: Schema.NullOr(Schema.String),
    id: Schema.String,
    publishedAt: Schema.String,
    slug: Schema.String,
    status: Schema.Literal("published"),
    tags: Schema.Array(Schema.String),
    title: Schema.String,
  }),
  PublicAuthor = Schema.Struct({
    biography: Schema.String,
    externalLinks: Schema.Array(Schema.JsonObject),
    id: Schema.String,
    name: Schema.String,
    portrait: Schema.NullOr(Schema.String),
    portraitAlternativeText: Schema.NullOr(Schema.String),
    profile: Schema.NullOr(RichTextDocument),
    slug: Schema.String,
  }),
  PublicTaxonomy = Schema.Struct({
    description: Schema.NullOr(Schema.String),
    id: Schema.String,
    name: Schema.String,
    slug: Schema.String,
  }),
  PublicEntryReference = Schema.Union([PublicPost, PublicAuthor, PublicTaxonomy]),
  PublicComment = Schema.Struct({
    body: Schema.String,
    createdAt: Schema.String,
    displayName: Schema.String,
    id: Schema.String,
    post: Schema.String,
    status: Schema.Literal("approved"),
    websiteUrl: Schema.NullOr(Schema.String),
  }),
  AssetMetadata = Schema.Struct({
    byteLength: Schema.Int,
    defaultAlternativeText: Schema.optionalKey(Schema.String),
    digest: Schema.String,
    filename: Schema.String,
    height: Schema.optionalKey(Schema.Int),
    mediaType: Schema.String,
    width: Schema.optionalKey(Schema.Int),
  }),
  PublicAsset = Schema.Struct({ id: Schema.String, metadata: AssetMetadata }),
  PublicBlogExport = Schema.Struct({
    assets: Schema.Array(PublicAsset),
    authors: Schema.Array(PublicAuthor),
    categories: Schema.Array(PublicTaxonomy),
    comments: Schema.Array(PublicComment),
    definitionFingerprint: Schema.String,
    generatedAt: Schema.String,
    posts: Schema.Array(PublicPost),
    tags: Schema.Array(PublicTaxonomy),
  }),
  CommentSubmission = Schema.Struct({
    body: Schema.String,
    displayName: Schema.String,
    websiteUrl: Schema.optionalKey(Schema.NullOr(Schema.String)),
  }),
  CommentReceipt = Schema.Struct({
    status: Schema.Literal("pending"),
    submissionId: Schema.String,
  }),
  EntryPage = (entry: Schema.Codec<unknown, unknown, never, never>) =>
    Schema.Struct({
      items: Schema.Array(entry),
      nextCursor: Schema.optionalKey(Schema.String),
    }),
  EntryRepresentation = Schema.Struct({
    contentTypeId: Schema.String,
    id: Schema.String,
    values: Schema.JsonObject,
  }),
  EntryState = Schema.Struct({
    entry: EntryRepresentation,
    revisionNumber: Schema.Int,
    writeToken: Schema.String,
  }),
  EditorialReceipt = EntryState,
  CascadeDeletionReceipt = Schema.Struct({
    deletedCommentCount: Schema.Int,
    deletedPostId: Schema.String,
  }),
  DetachmentReceipt = Schema.Struct({
    detachedPostCount: Schema.Int,
    removedEntryId: Schema.String,
  }),
  ImageReplacementRequest = Schema.Struct({
    content: Schema.Uint8Array,
    metadata: AssetMetadata,
  }),
  ImageReplacementReceipt = Schema.Struct({
    ingestionCompleted: Schema.Boolean,
    newAssetId: Schema.String,
    oldAssetDeleted: Schema.Boolean,
    oldAssetId: Schema.String,
    reassignedEntryCount: Schema.Int,
    reassignmentCompleted: Schema.Boolean,
  }),
  AssetBytes = Schema.Uint8Array;
