import { Schema } from "effect";

const foundationAssetBytes = Schema.Uint8Array,
  foundationAssetMetadata = Schema.Struct({
    byteLength: Schema.Int,
    defaultAlternativeText: Schema.optionalKey(Schema.String),
    digest: Schema.String,
    filename: Schema.String,
    height: Schema.optionalKey(Schema.Int),
    mediaType: Schema.String,
    width: Schema.optionalKey(Schema.Int),
  }),
  foundationCommentReceipt = Schema.Struct({
    status: Schema.Literal("pending"),
    submissionId: Schema.String,
  }),
  foundationCommentSubmission = Schema.Struct({
    body: Schema.String,
    displayName: Schema.String,
    websiteUrl: Schema.optionalKey(Schema.NullOr(Schema.String)),
  }),
  foundationDeletionRecord = Schema.Struct({
    contentTypeId: Schema.String,
    deletedAt: Schema.String,
    entryId: Schema.String,
    latestRevisionNumber: Schema.Int,
    writeToken: Schema.String,
  }),
  foundationEmptyRequest = Schema.Struct({}),
  foundationEntryRepresentation = Schema.Struct({
    contentTypeId: Schema.String,
    id: Schema.String,
    values: Schema.JsonObject,
  }),
  foundationIdentifier = Schema.String,
  foundationImageUploadMetadata = Schema.Struct({
    defaultAlternativeText: Schema.optionalKey(Schema.String),
    filename: Schema.String,
    height: Schema.optionalKey(Schema.Int),
    mediaType: Schema.String,
    width: Schema.optionalKey(Schema.Int),
  }),
  foundationPageQuery = {
    cursor: Schema.String,
    pageSize: Schema.Int,
  },
  foundationRichTextDocument = Schema.JsonObject,
  modelEntryPage = <Entry extends Schema.Codec<unknown, unknown>>(
    entry: Readonly<Entry>,
  ): Schema.Codec<unknown, unknown> =>
    Schema.Struct({
      items: Schema.Array(entry),
      nextCursor: Schema.optionalKey(Schema.String),
    }),
  modelEntryState = Schema.Struct({
    entry: foundationEntryRepresentation,
    revisionNumber: Schema.Int,
    writeToken: Schema.String,
  }),
  modelPublicAuthor = Schema.Struct({
    biography: Schema.String,
    externalLinks: Schema.Array(Schema.JsonObject),
    id: Schema.String,
    name: Schema.String,
    portrait: Schema.NullOr(Schema.String),
    portraitAlternativeText: Schema.NullOr(Schema.String),
    profile: Schema.NullOr(foundationRichTextDocument),
    slug: Schema.String,
  }),
  modelPublicComment = Schema.Struct({
    body: Schema.String,
    createdAt: Schema.String,
    displayName: Schema.String,
    id: Schema.String,
    post: Schema.String,
    status: Schema.Literal("approved"),
    websiteUrl: Schema.NullOr(Schema.String),
  }),
  modelPublicPost = Schema.Struct({
    author: Schema.String,
    body: foundationRichTextDocument,
    categories: Schema.Array(Schema.String),
    excerpt: Schema.String,
    featuredAlternativeText: Schema.NullOr(Schema.String),
    featuredAsset: Schema.NullOr(Schema.String),
    id: Schema.String,
    publishedAt: Schema.String,
    slug: Schema.String,
    status: Schema.Literal("published"),
    tags: Schema.Array(Schema.String),
    title: Schema.String,
  }),
  modelPublicGuide = Schema.Struct({
    body: foundationRichTextDocument,
    description: Schema.String,
    id: Schema.String,
    nextGuide: Schema.NullOr(Schema.String),
    slug: Schema.String,
    sortOrder: Schema.Int,
    status: Schema.Literal("published"),
    title: Schema.String,
  }),
  modelPublicTaxonomy = Schema.Struct({
    description: Schema.NullOr(Schema.String),
    id: Schema.String,
    name: Schema.String,
    slug: Schema.String,
  }),
  receiptAuthorCascadeDeletion = Schema.Struct({
    deletedAuthorId: Schema.String,
    deletedCommentCount: Schema.Int,
    deletedPostCount: Schema.Int,
    deletionRecord: foundationDeletionRecord,
  }),
  receiptCascadeDeletion = Schema.Struct({
    deletedCommentCount: Schema.Int,
    deletedPostId: Schema.String,
    deletionRecord: foundationDeletionRecord,
  }),
  receiptDetachment = Schema.Struct({
    deletionRecord: foundationDeletionRecord,
    detachedPostCount: Schema.Int,
    removedEntryId: Schema.String,
  }),
  receiptEditorial = modelEntryState,
  receiptImageDeletion = Schema.Struct({
    clearedAuthorCount: Schema.Int,
    clearedPostCount: Schema.Int,
    deletedAssetId: Schema.String,
    deletionCompleted: Schema.Boolean,
  }),
  receiptImageReplacementRequest = Schema.Struct({
    content: Schema.Uint8Array,
    metadata: foundationImageUploadMetadata,
  }),
  receiptImageReplacementResult = Schema.Struct({
    ingestionCompleted: Schema.Boolean,
    newAssetId: Schema.String,
    oldAssetDeleted: Schema.Boolean,
    oldAssetId: Schema.String,
    reassignedEntryCount: Schema.Int,
    reassignmentCompleted: Schema.Boolean,
  }),
  responsePublicAsset = Schema.Struct({ id: Schema.String, metadata: foundationAssetMetadata }),
  responsePublicEntryReference = Schema.Union([
    modelPublicPost,
    modelPublicAuthor,
    modelPublicTaxonomy,
  ]),
  zPublicBlogExport = Schema.Struct({
    assets: Schema.Array(responsePublicAsset),
    authors: Schema.Array(modelPublicAuthor),
    categories: Schema.Array(modelPublicTaxonomy),
    comments: Schema.Array(modelPublicComment),
    definitionFingerprint: Schema.String,
    generatedAt: Schema.String,
    guides: Schema.Array(modelPublicGuide),
    posts: Schema.Array(modelPublicPost),
    tags: Schema.Array(modelPublicTaxonomy),
  });

/** Runtime schemas for the Example CMS wire contract. */
export {
  foundationAssetBytes as AssetBytes,
  foundationAssetMetadata as AssetMetadata,
  receiptAuthorCascadeDeletion as AuthorCascadeDeletionReceipt,
  receiptCascadeDeletion as CascadeDeletionReceipt,
  foundationCommentReceipt as CommentReceipt,
  foundationCommentSubmission as CommentSubmission,
  foundationDeletionRecord as DeletionRecord,
  receiptDetachment as DetachmentReceipt,
  receiptEditorial as EditorialReceipt,
  foundationEmptyRequest as EmptyRequest,
  modelEntryPage as EntryPage,
  foundationEntryRepresentation as EntryRepresentation,
  modelEntryState as EntryState,
  foundationIdentifier as Identifier,
  receiptImageDeletion as ImageDeletionReceipt,
  receiptImageReplacementResult as ImageReplacementReceipt,
  receiptImageReplacementRequest as ImageReplacementRequest,
  foundationImageUploadMetadata as ImageUploadMetadata,
  foundationPageQuery as PageQuery,
  responsePublicAsset as PublicAsset,
  modelPublicAuthor as PublicAuthor,
  zPublicBlogExport as PublicBlogExport,
  modelPublicComment as PublicComment,
  modelPublicGuide as PublicGuide,
  responsePublicEntryReference as PublicEntryReference,
  modelPublicPost as PublicPost,
  modelPublicTaxonomy as PublicTaxonomy,
  foundationRichTextDocument as RichTextDocument,
};
